package com.ecnu.stldemo.elements.visitor;

import com.ecnu.stldemo.elements.abstracts.ExpressionOne;
import com.ecnu.stldemo.elements.element.Formula;
import com.ecnu.stldemo.elements.element.ParenExpression;
import com.ecnu.stldemo.elements.element.Perturbation;
import com.ecnu.stldemo.elements.element.Program;
import com.ecnu.stldemo.elements.element.expressionone.Eventually;
import com.ecnu.stldemo.elements.element.expressionone.Global;
import com.ecnu.stldemo.elements.element.expressionone.NotExpression;
import com.ecnu.stldemo.elements.element.expressiontwo.And;
import com.ecnu.stldemo.elements.element.expressiontwo.Imply;
import com.ecnu.stldemo.elements.element.expressiontwo.Or;
import com.ecnu.stldemo.elements.element.expressiontwo.Until;
import com.ecnu.stldemo.elements.element.predicates_Type.GEPredicate;
import com.ecnu.stldemo.elements.element.predicates_Type.GTPredicate;
import com.ecnu.stldemo.elements.element.predicates_Type.LEPredicate;
import com.ecnu.stldemo.elements.element.predicates_Type.LTPredicate;

/**
 * Visitor to visit STL expression elements(Not expression context generated by antlr)
 * @author wangyao2221
 * @date 2020/10/28 14:21
 */
public interface STLElementVisitor {
    String visitProgram(Program program);
    String visitFormula(Formula formula);
    String visitImply(Imply imply);
    String visitUtil(Until until);
    String visitAnd(And and);
    String visitUnaryExpression(ExpressionOne expressionOne);
    String visitParens(ParenExpression parens);
    String visitOr(Or or);
    String visitEventually(Eventually eventually);
    String visitGlobal(Global global);
    String visitNot(NotExpression not);
    String visitGT(GTPredicate gt);
    String visitLT(LTPredicate lt);
    String visitGE(GEPredicate ge);
    String visitLE(LEPredicate le);
    String visitPerturbation(Perturbation perturbation);
}
